// flow-typed signature: 93d0f9a47f88966af88c2d0d0cc48ff1
// flow-typed version: <<STUB>>/bignumber.js_v^4.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bignumber.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bignumber.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bignumber.js/bignumber' {
  declare module.exports: any;
}

declare module 'bignumber.js/bignumber.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bignumber.js/bignumber.js' {
  declare module.exports: $Exports<'bignumber.js/bignumber'>;
}
declare module 'bignumber.js/bignumber.min.js' {
  declare module.exports: $Exports<'bignumber.js/bignumber.min'>;
}
