// flow-typed signature: 9de87fb467ffd88cd7fed31ce23c6e16
// flow-typed version: <<STUB>>/command-line-args_v^4.0.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-line-args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-line-args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-line-args/bin/cli' {
  declare module.exports: any;
}

declare module 'command-line-args/example/mocha' {
  declare module.exports: any;
}

declare module 'command-line-args/example/type' {
  declare module.exports: any;
}

declare module 'command-line-args/example/typical' {
  declare module.exports: any;
}

declare module 'command-line-args/example/unknown' {
  declare module.exports: any;
}

declare module 'command-line-args/example/validate' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/argv' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/command-line-args' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/definition' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/grouped-output' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/option' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/output' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/output2' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/value-arg' {
  declare module.exports: any;
}

declare module 'command-line-args/test/alias' {
  declare module.exports: any;
}

declare module 'command-line-args/test/ambiguous-input' {
  declare module.exports: any;
}

declare module 'command-line-args/test/bad-input' {
  declare module.exports: any;
}

declare module 'command-line-args/test/class-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/test/class-definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/test/class-output' {
  declare module.exports: any;
}

declare module 'command-line-args/test/default-option' {
  declare module.exports: any;
}

declare module 'command-line-args/test/default-value' {
  declare module.exports: any;
}

declare module 'command-line-args/test/detect-process-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/test/exceptions' {
  declare module.exports: any;
}

declare module 'command-line-args/test/grouping' {
  declare module.exports: any;
}

declare module 'command-line-args/test/multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/test/name-alias-mix' {
  declare module.exports: any;
}

declare module 'command-line-args/test/name-unicode' {
  declare module.exports: any;
}

declare module 'command-line-args/test/notations' {
  declare module.exports: any;
}

declare module 'command-line-args/test/option' {
  declare module.exports: any;
}

declare module 'command-line-args/test/partial' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-boolean' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-none' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-number' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-other' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-line-args/bin/cli.js' {
  declare module.exports: $Exports<'command-line-args/bin/cli'>;
}
declare module 'command-line-args/example/mocha.js' {
  declare module.exports: $Exports<'command-line-args/example/mocha'>;
}
declare module 'command-line-args/example/type.js' {
  declare module.exports: $Exports<'command-line-args/example/type'>;
}
declare module 'command-line-args/example/typical.js' {
  declare module.exports: $Exports<'command-line-args/example/typical'>;
}
declare module 'command-line-args/example/unknown.js' {
  declare module.exports: $Exports<'command-line-args/example/unknown'>;
}
declare module 'command-line-args/example/validate.js' {
  declare module.exports: $Exports<'command-line-args/example/validate'>;
}
declare module 'command-line-args/lib/argv.js' {
  declare module.exports: $Exports<'command-line-args/lib/argv'>;
}
declare module 'command-line-args/lib/command-line-args.js' {
  declare module.exports: $Exports<'command-line-args/lib/command-line-args'>;
}
declare module 'command-line-args/lib/definition.js' {
  declare module.exports: $Exports<'command-line-args/lib/definition'>;
}
declare module 'command-line-args/lib/definitions.js' {
  declare module.exports: $Exports<'command-line-args/lib/definitions'>;
}
declare module 'command-line-args/lib/grouped-output.js' {
  declare module.exports: $Exports<'command-line-args/lib/grouped-output'>;
}
declare module 'command-line-args/lib/option.js' {
  declare module.exports: $Exports<'command-line-args/lib/option'>;
}
declare module 'command-line-args/lib/output.js' {
  declare module.exports: $Exports<'command-line-args/lib/output'>;
}
declare module 'command-line-args/lib/output2.js' {
  declare module.exports: $Exports<'command-line-args/lib/output2'>;
}
declare module 'command-line-args/lib/value-arg.js' {
  declare module.exports: $Exports<'command-line-args/lib/value-arg'>;
}
declare module 'command-line-args/test/alias.js' {
  declare module.exports: $Exports<'command-line-args/test/alias'>;
}
declare module 'command-line-args/test/ambiguous-input.js' {
  declare module.exports: $Exports<'command-line-args/test/ambiguous-input'>;
}
declare module 'command-line-args/test/bad-input.js' {
  declare module.exports: $Exports<'command-line-args/test/bad-input'>;
}
declare module 'command-line-args/test/class-argv.js' {
  declare module.exports: $Exports<'command-line-args/test/class-argv'>;
}
declare module 'command-line-args/test/class-definitions.js' {
  declare module.exports: $Exports<'command-line-args/test/class-definitions'>;
}
declare module 'command-line-args/test/class-output.js' {
  declare module.exports: $Exports<'command-line-args/test/class-output'>;
}
declare module 'command-line-args/test/default-option.js' {
  declare module.exports: $Exports<'command-line-args/test/default-option'>;
}
declare module 'command-line-args/test/default-value.js' {
  declare module.exports: $Exports<'command-line-args/test/default-value'>;
}
declare module 'command-line-args/test/detect-process-argv.js' {
  declare module.exports: $Exports<'command-line-args/test/detect-process-argv'>;
}
declare module 'command-line-args/test/exceptions.js' {
  declare module.exports: $Exports<'command-line-args/test/exceptions'>;
}
declare module 'command-line-args/test/grouping.js' {
  declare module.exports: $Exports<'command-line-args/test/grouping'>;
}
declare module 'command-line-args/test/multiple.js' {
  declare module.exports: $Exports<'command-line-args/test/multiple'>;
}
declare module 'command-line-args/test/name-alias-mix.js' {
  declare module.exports: $Exports<'command-line-args/test/name-alias-mix'>;
}
declare module 'command-line-args/test/name-unicode.js' {
  declare module.exports: $Exports<'command-line-args/test/name-unicode'>;
}
declare module 'command-line-args/test/notations.js' {
  declare module.exports: $Exports<'command-line-args/test/notations'>;
}
declare module 'command-line-args/test/option.js' {
  declare module.exports: $Exports<'command-line-args/test/option'>;
}
declare module 'command-line-args/test/partial.js' {
  declare module.exports: $Exports<'command-line-args/test/partial'>;
}
declare module 'command-line-args/test/type-boolean.js' {
  declare module.exports: $Exports<'command-line-args/test/type-boolean'>;
}
declare module 'command-line-args/test/type-none.js' {
  declare module.exports: $Exports<'command-line-args/test/type-none'>;
}
declare module 'command-line-args/test/type-number.js' {
  declare module.exports: $Exports<'command-line-args/test/type-number'>;
}
declare module 'command-line-args/test/type-other.js' {
  declare module.exports: $Exports<'command-line-args/test/type-other'>;
}
declare module 'command-line-args/test/type-string.js' {
  declare module.exports: $Exports<'command-line-args/test/type-string'>;
}
