// flow-typed signature: b4a9cdac98d3624612f5091aa15a8ed7
// flow-typed version: <<STUB>>/command-line-usage_v^4.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-line-usage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-line-usage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-line-usage/lib/command-line-usage' {
  declare module.exports: any;
}

declare module 'command-line-usage/lib/content-section' {
  declare module.exports: any;
}

declare module 'command-line-usage/lib/content' {
  declare module.exports: any;
}

declare module 'command-line-usage/lib/option-list' {
  declare module.exports: any;
}

declare module 'command-line-usage/lib/section' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-line-usage/lib/command-line-usage.js' {
  declare module.exports: $Exports<'command-line-usage/lib/command-line-usage'>;
}
declare module 'command-line-usage/lib/content-section.js' {
  declare module.exports: $Exports<'command-line-usage/lib/content-section'>;
}
declare module 'command-line-usage/lib/content.js' {
  declare module.exports: $Exports<'command-line-usage/lib/content'>;
}
declare module 'command-line-usage/lib/option-list.js' {
  declare module.exports: $Exports<'command-line-usage/lib/option-list'>;
}
declare module 'command-line-usage/lib/section.js' {
  declare module.exports: $Exports<'command-line-usage/lib/section'>;
}
