// flow-typed signature: fcb58a75548d5b68d4741d860daa1653
// flow-typed version: <<STUB>>/eth-lightwallet_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eth-lightwallet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eth-lightwallet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eth-lightwallet/dist/lightwallet' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/dist/lightwallet.min' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/example/example_usage' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/lib/encryption' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/lib/keystore' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/lib/signing' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/lib/txutils' {
  declare module.exports: any;
}

declare module 'eth-lightwallet/lib/upgrade' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eth-lightwallet/dist/lightwallet.js' {
  declare module.exports: $Exports<'eth-lightwallet/dist/lightwallet'>;
}
declare module 'eth-lightwallet/dist/lightwallet.min.js' {
  declare module.exports: $Exports<'eth-lightwallet/dist/lightwallet.min'>;
}
declare module 'eth-lightwallet/example/example_usage.js' {
  declare module.exports: $Exports<'eth-lightwallet/example/example_usage'>;
}
declare module 'eth-lightwallet/index' {
  declare module.exports: $Exports<'eth-lightwallet'>;
}
declare module 'eth-lightwallet/index.js' {
  declare module.exports: $Exports<'eth-lightwallet'>;
}
declare module 'eth-lightwallet/lib/encryption.js' {
  declare module.exports: $Exports<'eth-lightwallet/lib/encryption'>;
}
declare module 'eth-lightwallet/lib/keystore.js' {
  declare module.exports: $Exports<'eth-lightwallet/lib/keystore'>;
}
declare module 'eth-lightwallet/lib/signing.js' {
  declare module.exports: $Exports<'eth-lightwallet/lib/signing'>;
}
declare module 'eth-lightwallet/lib/txutils.js' {
  declare module.exports: $Exports<'eth-lightwallet/lib/txutils'>;
}
declare module 'eth-lightwallet/lib/upgrade.js' {
  declare module.exports: $Exports<'eth-lightwallet/lib/upgrade'>;
}
